AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - features/support/utils.rb
    - features/support/hooks.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 250

Style/GlobalVars:
  Enabled: false

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize: 
  Max: 45

Metrics/MethodLength: 
  Max: 35

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/ClassLength:
  Max: 150

Style/ClassVars:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false